CREATE TABLE car_listings (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  seller_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  make              VARCHAR(64),
  model             VARCHAR(64),
  trim              VARCHAR(64),
  year              INT,
  vin               VARCHAR(17),
  body_type         VARCHAR(32),
  color             VARCHAR(32),
  mileage_km        INT,
  price             NUMERIC(12,2),
  description       TEXT,
  contact_email     VARCHAR(320),
  contact_phone     VARCHAR(32),
  status            listing_status NOT NULL DEFAULT 'draft',
  published_at      TIMESTAMPTZ,
  removed_at        TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
);
