apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmotor-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: openmotor-backend
  template:
    metadata:
      labels:
        app: openmotor-backend
    spec:
      containers:
        - name: openmotor-backend
          image: registry.digitalocean.com/ece1779-team26-cr/openmotor-backend:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
            - name: API_BASE_PATH
              value: "/api/v1"
            - name: DB_HOST
              value: openmotor-db-service
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: openmotor_db
            - name: DB_USER
              value: openmotor_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openmotor-db-secret
                  key: POSTGRES_PASSWORD
            - name: JWT_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: openmotor-backend-secret
                  key: JWT_ACCESS_SECRET
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: openmotor-backend-secret
                  key: JWT_REFRESH_SECRET
            - name: ACCESS_TOKEN_TTL
              value: "15m"
            - name: REFRESH_TOKEN_TTL
              value: "7d"
            - name: AUTO_FLAG_THRESHOLD
              value: "3"
            - name: UPLOAD_DIR
              value: "/storage/uploads" 
          volumeMounts:
            - name: openmotor-backend-image-storage
              mountPath: /storage/uploads
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
          - name: openmotor-backend-image-storage
            persistentVolumeClaim:
              claimName: openmotor-backend-pvc